dist: trusty
language: node_js
node_js:
  - "13"

branches:
  only:
  - master

script:
  # - ng test --watch false -cc
  # - ng e2e
  # - ng build --prod --base-href="https://sebastienblanchet.github.io/portfolio"
  vue-cli-service build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
