language: node_js
node_js:
  - "7"
sudo: true
dist: trusty

branches:
  only:
  - master

script: 
  - ng test --watch false -cc
  - npm run e2e
  - ng build -bh "https://sebastienblanchet.github.io/portfolio/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
